main : main.c CIpostings.o CIvocab.c CIdoclist.c CI.c CI.h CIpostings.h
	g++ -O3 -o main main.c CIpostings.o CIvocab.c CIdoclist.c CI.c


CIpostings.o : CIpostings/makefile
	cd CIpostings && make && cd ..

