main : main.c CIpostings.o CIvocab.c CIdoclist.c CI.c CI.h CIpostings.h
	g++ -o main CIpostings.o -x c++ -O3 main.c CIvocab.c CIdoclist.c CI.c


CIpostings.o : CIpostings/makefile
	cd CIpostings && make && cd ..

